base/urls.py
from django.urls import path
from .views import ( home,
                    room,
                    create_room,
                    update_room,
                    delete_room,
                    delete_message,
                    topics_view,
                    activities_view
                    )

app_name = 'base'

urlpatterns = [
    path('',home, name='home'),
    path('room/<str:pk>/',room, name='room'),
    path('create-room/',create_room, name='create_room' ),
    path('update-room/<int:pk>/',update_room, name='update_room' ),
    path('delete-room/<int:pk>/',delete_room, name='delete_room' ),
    path('delete-message/<int:pk>/',delete_message, name='delete_message' ),
    path('topics',topics_view,name='topics'),
    path('activities',activities_view,name='activities')

]

blog/urls.py
from django.urls import path
from .views import (
    HomeListView,
    LikePost,
    PostDetailView,
    AddPostView,
    UpdatePostView,
    DeletePostView,
    LikePost
)

app_name = 'blog'
urlpatterns = [
    path('',HomeListView.as_view(),name='home'),
    path('post/<str:slug>/',PostDetailView.as_view(),name='post_detail'),
    path('add-post/',AddPostView.as_view(),name='post_add'),
    path('update-post/<str:slug>/',UpdatePostView.as_view(),name='post_update'),
    path('delete-post/<str:slug>/',DeletePostView.as_view(),name='post_delete'),
    path('like/',LikePost,name='like_post')

]

study_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from base.admin import base_site

urlpatterns = [
    path('admin/',admin.site.urls),
    path('base-admin/',base_site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('rooms/',include('base.urls')),
    path('',include('blog.urls')),
    path('summernote/',include('django_summernote.urls')),
    path('api/', include('base.api.api_urls')),
    path('users/',include('users.urls')),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html',),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    
admin.site.index_title = 'The Study Blog'
admin.site.site_header = 'The Study Blog Administrations'
admin.site.site_title = 'Sudy Blog Admin'

users/urls.py
from os import name
from django.urls import path,reverse_lazy
from .views  import (
    login_page,
    logout_user,
    register_page,
    userProfile,
    editUser,
    password_success,
    PasswordsChangeView
     
                        )

app_name = 'users'

urlpatterns = [
    path('login/',login_page,name='login'),
    path('logout/',logout_user,name='logout'),
    path('register/',register_page,name='register'),
    path('profile/<str:pk>',userProfile,name='user-profile'),
    path('edit-user/<int:pk>/',editUser, name='edit_user' ),
    path('change-password/',PasswordsChangeView.as_view(), name='change_password'),
    path('password/success/',password_success,name='password_success'),
    






]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel,TreeForeignKey


class Post(models.Model):
    title = models.CharField(max_length=220, help_text='This  title is required')
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title_tag = models.CharField(max_length=220,unique=True,blank=True,help_text='automatically maded')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User,related_name='blog_post')
    body = models.TextField(blank=True,null=True)

    def __str__(self):
        return f'Post "{self.title}"'
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug':self.title_tag})
    
    def save(self,*args,**kwargs):
        try:
            a = Post.objects.all().last().id
        except:
            a = 0
        self.title_tag = f"{self.title.replace(' ', '-')}-{a+1}-{self.author.id}"
        super().save(*args,**kwargs)
    class Meta:
        ordering = ['-created']
        
class Comment(MPTTModel):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    parent = TreeForeignKey('self',on_delete=models.CASCADE, null=True,blank=True,related_name='children')
    writer = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['created']
        
    def __str__(self):
        return f'Comment "{self.content[:50]}" by {self.writer.username}'

blog/forms.py
from xml.dom.minidom import Comment
from django.forms import ModelForm
from .models import Comment
from mptt.forms import TreeNodeChoiceField


class CommentForm(ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['parent'].required = False
        self.fields['parent'].widget.attrs.update({'class':'d-none'})
    class Meta:
        model = Comment
        fields = ['content','parent']
        

blog/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.urls.converters import SlugConverter
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Post, Comment
from django.views.generic.edit import FormMixin
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import CommentForm


def LikePost(request):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return HttpResponseRedirect(reverse('blog:post_detail', args=[post.title_tag]))


class HomeListView(ListView):
    model = Post
    paginate_by = 2

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            obj_list = self.model.objects.filter(Q(title__icontains=query) |
                                                 Q(body__icontains=query) |
                                                 Q(author__username__icontains=query))
        else:
            obj_list = self.model.objects.all()
        return obj_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['popular_posts'] = Post.objects.all().order_by('-likes')[:5]
        return context


class PostDetailView(FormMixin, DetailView):
    model = Post
    slug_field = 'title_tag'
    form_class = CommentForm

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.title_tag})

    def get_context_data(self, *args, **kwargs):
        like_post = get_object_or_404(Post, title_tag=self.kwargs['slug'])
        context = super(PostDetailView, self).get_context_data(*args, **kwargs)
        liked = False
        if like_post.likes.filter(id=self.request.user.id).exists():
            liked = True
        context['liked'] = liked
        context['form'] = CommentForm(initial={'post': self.object})
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.writer_id = self.request.user.id
        form.instance.post = self.get_object()

        form.save()
        return super().form_valid(form)


class AddPostView(LoginRequiredMixin, CreateView):
    model = Post
    login_url = reverse_lazy('users:login')
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdatePostView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    slug_field = 'title_tag'
    fields = ['title', 'body']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['update'] = True
        return context

    def test_func(self):
        if self.get_object().author == self.request.user:
            return True
        else:
            return False


class DeletePostView(DeleteView):
    model = Post
    slug_field = 'title_tag'
    success_url = reverse_lazy('blog:home')

blog/templates/blog/post_confirm_delete.html
{% extends 'main.html' %}
{% block title %} Delete Post {% endblock %}
{% block content%}
 

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
<p>Are you sure to delete {{object.title}}</p>
<button >Delete Post</button>
</form>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'main.html' %}
{% block title %} Post Detail {% endblock %}
{% block content%}

<div class="room">
  <div class="room__top">
    <div class="room__topLeft">
      <a href="{% url 'base:home' %}">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>arrow-left</title>
          <path
            d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
          ></path>
        </svg>
      </a>
      <h3>Post  "{{object.title}}"</h3>
    </div>
        {% if room.author == user %}
    <div class="room__topRight">
      <a href="{% url 'blog:post_update' post.title_tug %}">
        <svg
          enable-background="new 0 0 24 24"
          height="32"
          viewBox="0 0 24 24"
          width="32"
          xmlns="http://www.w3.org/2000/svg"
        >
          <title>edit</title>
          <g>
            <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
          </g>
          <g>
            <g>
              <path
                d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
              />
            </g>
            <g>
              <path
                d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
              />
            </g>
          </g>
        </svg>
      </a>
      <a href="#">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>remove</title>
          <path
            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
          ></path>
        </svg>
      </a>
    </div>
    {% endif %}


  </div>
  <div class="room__box scroll">
    <div class="room__header scroll">
      <div class="room__info">
        <h3>{{post.title}}</h3>
        <span>{{ post.created|timesince }}</span>
      </div>
      <div class="room__hosted">
        <p>Hosted By</p>
        <a href="{% url 'users:user-profile' post.author.id %}" class="room__author">
          <div class="avatar avatar--small">
            <img src="{{post.author.profile.image.url}}" />
          </div>
          <span>@{{post.author.username}}</span>
        </a>
      </div>
      <div class="room__details">
        {{ post.body }}
        
      </div>
      
        <form action="{% url 'blog:like_post' %}" method="post">
        {% csrf_token %}

        
        {% if liked %}
        <button name="post_id" value="{{post.id}}" style="color: brown; background-color:rgb(53, 53, 88)" class="btn btn-counter" ><span>&#x2764;</span></button>
        <span class="room__topics">{{post.likes.count}}</span>
      
      {% else %}
      <button name="post_id" value="{{post.id}}" style="color: rgb(107, 107, 107); background-color:rgb(53, 53, 88)" class="btn btn-counter" ><span>&#x2764;</span></button>
        <span class="room__topics">{{post.likes.count}}</span>

      {% endif %}
    </form>
      <div style="margin: 10px;">Comments {{post.comment_set.all.count}}</div>
    </div>
    
    <div class="room__conversation">
      <div class="threads scroll">
        {% load mptt_tags %}
        {% if post.comment_set.all %}
        {% recursetree post.comment_set.all %}
        <div class="my-2 p-2" style="border: 1px solid grey;">
        <div class="thread">
          <div class="thread__top">
            <div class="thread__author">
              <a href="{% url 'users:user-profile' node.writer.id %}" class="thread__authorInfo">
                <div class="avatar avatar--small">
                  <img src="{{ node.writer.profile.image.url }}" />
                </div>
                <span>@{{node.writer}}</span>
              </a> 
              <button class="btn btn-outline-info" style="background-color: rgb(59, 59, 92); " onclick="myFunction({{node.id}})">Reply</button>
              <span class="thread__date">{{node.created|timesince}}</span>
            </div>
            
            <a href="#">
            <div class="thread__delete">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>remove</title>
                <path
                  d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                ></path>
              </svg>
            </div>
          </a>
         
          </div>
          <div id="{{node.id}}" class="thread__details">
            {{node.content}}
            
          </div>
        </div> 
      </div>
        {% if not node.is_leaf_node %} 
        <div  class="children p1-2 pl-md-5">
          {{children}}
        </div>
        {% endif %}
        {% endrecursetree %}
      </div>
    </div>
  </div>
  {% else %}   
  <br>
  <br>
        <p>No Comments</p>
  {% endif %} 
  <div class="room__message">
    <form id="myForm" action="" method="post">
      {% csrf_token%}
     <input  name="content" placeholder="Write your comment here..." />
        {{form.parent}}
    </form>
  </div>
</div>

<script>
  function formExit() {
    document.getElementById('newForm').remove();
  }
  function myFunction(id) {
    if (document.contains(document.getElementById('newForm'))){
      document.getElementById('newForm').remove();
    }
    var a = document.getElementById(id);
    a.insertAdjacentHTML('afterend','<form id="newForm" method="post">\
      <div class="d-flex justify-content-between"><h2>Reply:</h2><div><button type="button" style="background-color: rgb(59, 59, 92); " class="btn btn-outline-secondary" onclick="formExit()">Close</button></div></div>\
      <input type="hidden" name="csrfmiddlewaretoken" value="HMkjvTm6y6toukgnl16ymgrmmnRxE33FyjctimptkcCKMrwEkFfyktsHLKPqWFr5">\
      <input style="background-color: rgb(67, 67, 114); color: rgb(189, 186, 186);"  class="form-control " name="content" placeholder="Write your comment here...">\
      <select name="parent" class="d-none" id="id_parent">\
        <option value="'+ id + '" selected="' + id + '"></option>\
      </select>\
      {% csrf_token%} \
      </form>' );
  };
$('#myForm').trigger('reset');
</script>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'main.html' %}
{% block title %} Add Post {% endblock %}
{% block content%}
 
<div class="layout__body">
    <form class="form" action="" method="post">
      {% csrf_token %}
      
      <div class="form__group">
        <label for="room_topic">Title</label>
        {{form.title}}
      </div>

      <div class="form__group">
        <label for="room_name">Body</label>
          {{form.body}}
      </div>
      <div class="form__action">
        <a class="btn btn--dark" href="{% url 'blog:home' %}">Cancel</a>
        <button class="btn btn--main" type="submit">{% if update %} Update Post {% else %} Add Post {% endif %}</button>
      </div>
    </form>
    
  </div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'main.html' %}
{% block title %} Posts {% endblock %}
{% block content %} 
    <main class="profile-page layout layout--2">
      <div class="container">
        <!-- Room Start -->
        <div >
        
          <div style="margin:15px 0px 0px 45px">
            <a class="btn btn--main" href="{% url 'blog:post_add' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Add Post
            </a>
            <a class="btn btn--main" href="{% url 'base:home' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="27" height="32" viewBox="0 0 32 32">
                <title>add</title>
                
              </svg>
              Study Rooms
            </a>
          </div>
          {% if post_list %}
          {% for post in post_list %} 
          <div class="container" style="margin-top: 20px;">
          <div class="roomListRoom">
              <div class="roomListRoom__header">
                <a href="{% url 'users:user-profile' post.author.id %}" class="roomListRoom__author">
                  <div class="avatar avatar--small active ">
                    <img src="{{post.author.profile.image.url}}" />
                  </div>
                  <span>@{{post.author.username}} </span>
                </a>
                <div class="roomListRoom__actions">
                  <span>{{post.created|timesince}}</span>
                </div>
              </div>
              <div class="roomListRoom__content">
                <a href="{% url 'blog:post_detail' post.title_tag %}">{{ post.title }}</a>
                <p>
                  {{post.body|slice:':200'}}
                </p>
              </div>
              <div class="roomListRoom__meta">
                <a class="roomListRoom__joined">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>user-group</title>
                    <path
                      d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
                    ></path>
                    <path
                      d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
                    ></path>
                    <path
                      d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
                    ></path>
                    <path
                      d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
                    ></path>
                  </svg>
                   Joined
                </a>
                {% if user == post.author %}
                <a href="{% url 'blog:post_update' post.title_tag %}">Update</a>
                <a href="{% url 'blog:post_delete' post.title_tag %}">Delete</a>
                {% endif %}
                
              </div>
            </div>
            </div>
            {% endfor %}
          {% else %}
          <div>
            <h2 style="margin:60px;">0 Post Available</h2>
          </div>
          {% endif %}
         
           <!-- Startp Pagination -->
           {% include 'paginator.html' %}
           <!-- End Pagination -->
        </div>
         
        <!-- Room End -->
        <div class="activities">
          <div class="activities__header">
            <h2>Popular Posts</h2>
          </div>
          {% for post in popular_posts %}

            <div class="activities__box">
              <div class="activities__boxHeader roomListRoom__header">
                <a href="{% url 'users:user-profile' post.author.id %}" class="roomListRoom__author">
                  <div class="avatar avatar--small active">
                    <img src="{{post.author.profile.image.url}}" />
                  </div>
                  <p>
                    @{{post.author}}
                    <span>{{post.created|timesince}}</span>
                  </p>
                </a>
                
               {% if user == post.author %}
               <div class="roomListRoom__actions">
                  
                <a href="{% url 'blog:post_delete' post.id %}">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>remove</title>
                    <path
                      d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                    ></path>
                  </svg>
                </a>
              </div>
                {% endif %}
            
             
              </div>
              <p><a href="{% url 'blog:post_detail' post.title_tag %}">{{post.title}}</a></p>
              <div class="activities__boxContent">
               
                <div class="activities__boxRoomContent">
                  {{post.body|slice:':140'}}...
                </div>
              </div>
            </div>
            {% endfor %}
             

        </div>
      
      </div>
    </main>

{% endblock %}