base/urls.py
from django.urls import path
from .views import ( home,
                    room,
                    create_room,
                    update_room,
                    delete_room,
                    delete_message,
                    topics_view,
                    activities_view
                    )

app_name = 'base'

urlpatterns = [
    path('',home, name='home'),
    path('room/<str:pk>/',room, name='room'),
    path('create-room/',create_room, name='create_room' ),
    path('update-room/<int:pk>/',update_room, name='update_room' ),
    path('delete-room/<int:pk>/',delete_room, name='delete_room' ),
    path('delete-message/<int:pk>/',delete_message, name='delete_message' ),
    path('topics',topics_view,name='topics'),
    path('activities',activities_view,name='activities')

]

blog/urls.py
from django.urls import path
from .views import (
    HomeListView,
    LikePost,
    PostDetailView,
    AddPostView,
    UpdatePostView,
    DeletePostView,
    LikePost
)

app_name = 'blog'
urlpatterns = [
    path('',HomeListView.as_view(),name='home'),
    path('post/<str:slug>/',PostDetailView.as_view(),name='post_detail'),
    path('add-post/',AddPostView.as_view(),name='post_add'),
    path('update-post/<str:slug>/',UpdatePostView.as_view(),name='post_update'),
    path('delete-post/<str:slug>/',DeletePostView.as_view(),name='post_delete'),
    path('like/',LikePost,name='like_post')

]

study_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from base.admin import base_site

urlpatterns = [
    path('admin/',admin.site.urls),
    path('base-admin/',base_site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('rooms/',include('base.urls')),
    path('',include('blog.urls')),
    path('summernote/',include('django_summernote.urls')),
    path('api/', include('base.api.api_urls')),
    path('users/',include('users.urls')),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html',),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    
admin.site.index_title = 'The Study Blog'
admin.site.site_header = 'The Study Blog Administrations'
admin.site.site_title = 'Sudy Blog Admin'

users/urls.py
from os import name
from django.urls import path,reverse_lazy
from .views  import (
    login_page,
    logout_user,
    register_page,
    userProfile,
    editUser,
    password_success,
    PasswordsChangeView
     
                        )

app_name = 'users'

urlpatterns = [
    path('login/',login_page,name='login'),
    path('logout/',logout_user,name='logout'),
    path('register/',register_page,name='register'),
    path('profile/<str:pk>',userProfile,name='user-profile'),
    path('edit-user/<int:pk>/',editUser, name='edit_user' ),
    path('change-password/',PasswordsChangeView.as_view(), name='change_password'),
    path('password/success/',password_success,name='password_success'),
    






]

templates/main.html
<!DOCTYPE html>
{% load static %} 
{% load recaptcha3 %} 
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    {% recaptcha_init %} 
    {% recaptcha_ready action_name='homepage' %} 
    <title>{% block title %}  {% endblock title %}</title>
  </head>

  <body>
   

    {% include 'navbar.html' %}
    {% block content %}

    {% endblock %}
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/navbar.html
{% load static %} 
 <header class="header header--loggedIn">
    <div class="container">
      <a href="{% url 'blog:home' %}" class="header__logo">
        <img src="{% static 'logo.svg' %}" />
        <h1>Study</h1>
      </a>
      <form class="header__search" action="" method="get" >
        <label>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>search</title>
            <path
              d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
            ></path>
          </svg>
          <input type="text" name='q' placeholder="Search for rooms..." />
        </label>
      </form>
      <nav class="header__menu">
        
      
          <!-- Logged In -->
          {% if user.is_authenticated %} 
          <div class="header__user">
            <a href="{% url 'users:user-profile' user.id %}">
              <div class="avatar avatar--medium active">
                <img src="{{user.profile.image.url}}" />
              </div>
              <p>{{user.first_name}} {{user.last_name}}<span>@{{user.username}}</span></p>
            </a>
            <button class="dropdown-button">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>chevron-down</title>
                <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
              </svg>
            </button>
          </div>  
      
          <div class="dropdown-menu" >
            <a href="{% url 'users:edit_user' user.id %}" class="dropdown-link"
              ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>tools</title>
                <path
                  d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z"
                ></path>
              </svg>
              Settings</a
            >
            <a href="{% url 'users:logout' %}" class="dropdown-link"
              ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>sign-out</title>
                <path
                  d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z"
                ></path>
                <path
                  d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z"
                ></path>
              </svg>
              Logout</a
            >
          </div>
        {% else %} 
          <a href="{% url 'users:login' %}">
            
            <p>Login</p>
          </a>
          <a href="{% url 'users:register' %}">
           
            <p>Sign up</p>
          </a>
          {% endif %} 
        </nav>
    </div>
  </header>

templates/paginator.html
<div class="pagination" >
    <nav aria-label="...">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item" >
          <a class="page-link" href="?page={{page_obj.previous_page_number}}" >Previous</a>
        </li>
        {%else %}
        <li class="page-item disabled">
          <a class="page-link" tabindex="-1">Previous</a>
        </li>
        {% endif %}
        {% for page in page_obj.paginator.page_range %} 
        {% if page_obj.number == page %} 
        <li class="page-item active">
          <a class="page-link" href="?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
        </li>
        {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
        <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item" >
          <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled" >
          <a class="page-link" tabindex="-1">Next</a>
        </li>
        {% endif %} 
      </ul>
    </nav>
   </div>

templates/room.html
{% extends 'main.html' %}
{% block title %} Room Page {% endblock title%}

{% block content%}
<h1>Room Page</h1>
{% endblock %}