base/urls.py
from django.urls import path
from .views import ( home,
                    room,
                    create_room,
                    update_room,
                    delete_room,
                    delete_message,
                    topics_view,
                    activities_view
                    )

app_name = 'base'

urlpatterns = [
    path('',home, name='home'),
    path('room/<str:pk>/',room, name='room'),
    path('create-room/',create_room, name='create_room' ),
    path('update-room/<int:pk>/',update_room, name='update_room' ),
    path('delete-room/<int:pk>/',delete_room, name='delete_room' ),
    path('delete-message/<int:pk>/',delete_message, name='delete_message' ),
    path('topics',topics_view,name='topics'),
    path('activities',activities_view,name='activities')

]

study_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from base.admin import base_site

urlpatterns = [
    path('admin/',admin.site.urls),
    path('base-admin/',base_site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('rooms/',include('base.urls')),
    path('',include('blog.urls')),
    path('summernote/',include('django_summernote.urls')),
    path('api/', include('base.api.api_urls')),
    path('users/',include('users.urls')),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html',),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    
admin.site.index_title = 'The Study Blog'
admin.site.site_header = 'The Study Blog Administrations'
admin.site.site_title = 'Sudy Blog Admin'

users/urls.py
from os import name
from django.urls import path,reverse_lazy
from .views  import (
    login_page,
    logout_user,
    register_page,
    userProfile,
    editUser,
    password_success,
    PasswordsChangeView
     
                        )

app_name = 'users'

urlpatterns = [
    path('login/',login_page,name='login'),
    path('logout/',logout_user,name='logout'),
    path('register/',register_page,name='register'),
    path('profile/<str:pk>',userProfile,name='user-profile'),
    path('edit-user/<int:pk>/',editUser, name='edit_user' ),
    path('change-password/',PasswordsChangeView.as_view(), name='change_password'),
    path('password/success/',password_success,name='password_success'),
    






]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.db.models.fields import TextField
from django.urls import reverse

class Profile(models.Model):
    ROLE_CHOICES = (
        (1,'User'),
        (2,'Supplier'),
        (3,'Admin'),
        (4,'SuperUser')
    )
    user = models.OneToOneField(User,on_delete=CASCADE)
    image = models.ImageField(default='default.jpg',upload_to='avatar/')
    bio = TextField(null=True,blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES,null=True,blank=True)

    @property
    def email(self):
        return f'{self.user.email}'


    def __str__(self):
        return f'{self.user.username}'
    
class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
class Room(models.Model):
    host =  models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic,on_delete=models.SET_NULL, null=True,)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-updated','-created']
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('base:room', kwargs={'pk':self.id})

class Message(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[:50] + '...'

    class Meta:
        ordering = ['-updated','-created']

base/forms.py
from django.db import models
from django.forms import ModelForm
from .models import Room
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from snowpenguin.django.recaptcha3.fields import ReCaptchaField



class RoomForm(ModelForm):
    captcha = ReCaptchaField()
    class Meta:
        model = Room
        fields = ['name','description','topic','captcha']

base/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Message, Room, Topic,Profile
from .forms import RoomForm
from django.db.models import Q
from django.contrib.auth.models import User                      
from django.contrib import messages
from django.core.paginator import Paginator



def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(Q(topic__name__icontains=q)|
                                Q(name__icontains=q)|
                                Q(description__icontains=q))
    
    paginator = Paginator(rooms,3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    topic = Topic.objects.all()
    room_count = rooms.count()
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))[:7]
    context = {
                'topic':topic,
                'room_count':room_count,
                'room_messages':room_messages,
                'page_obj':page_obj
                }
    
    return render(request,'home.html',context=context)

def room(request,pk):
    room = Room.objects.get(id=pk)
    messages = room.message_set.all().order_by('-created')
    participants = room.participants.all()
    if request.method == 'POST':
        message = Message.objects.create(
            user = request.user,
            room=room,
            body = request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('base:room',pk=room.id)
    context = {
        'room':room,
        'messages':messages,
        'participants':participants,
    }    
    return render(request,'room.html',context)



@login_required(login_url='users:login')
def create_room(request):
    form = RoomForm()
    topics = Topic.objects.all()
    if request.method == "POST":
        topic,created = Topic.objects.get_or_create(name=request.POST.get('topic')) 
        a = Room.objects.create(
            name= request.POST.get('name'),
            host= request.user,
            description= request.POST.get('description'),
            topic= topic,
        )
        return redirect(a.get_absolute_url())
        
            

    context = {'form':form,'topics':topics}
    return render(request,'create-room.html',context)


@login_required(login_url='base:login')
def update_room(request,pk):
    topics = Topic.objects.all()
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    if request.user != room.host:
        return HttpResponse('You are not allowed here! Only room authors can to update info.')
    if request.method  == "POST":
       
        topic,created = Topic.objects.get_or_create(name=request.POST.get('topic')) 
        room.topic = topic
        room.name = request.POST.get('name')
        room.description = request.POST.get('description')
        room.save()
        return redirect(room.get_absolute_url())
    context = {'form':form,'topics':topics,'room':room}
    return render(request, 'create_update_room.html', context)

@login_required(login_url='base:login')
def delete_room(request,pk):
    room = Room.objects.get(id=pk)
    if request.user != room.host:
        return HttpResponse('You are not allowed here! Only room authors can to delete room .')
    if request.method == 'POST':
        room.delete()
        return redirect('base:home')
    return render(request, 'delete.html',{'obj':room})


@login_required(login_url='base:login')
def delete_message(request,pk):
    message = Message.objects.get(id=pk)
    if request.user != message.user:
        return HttpResponse('You are not allowed here! Only message authors can to delete message.')
    if request.method == 'POST':
        message.delete()
        return redirect('base:home')
    return render(request, 'delete.html',{'obj':message})




def topics_view(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ""
    topics = Topic.objects.filter(name__icontains=q)
    context = {'topics':topics}
    return render(request,'topics.html',context=context)


def activities_view(request):
    messages = Message.objects.all()[:6]
    context = {'messages':messages}
    return render(request,'activity.html',context=context)

base/templates/base/activity_component.html
<!-- <h3>Recent Activity</h3>
        <hr>
        
            <div>
                <small>@{{message.user}} {{message.created|timesince}}</small>
                <small>replied to "{{message.room}}"</small>
                <p>{{message}}</p>
                                {% if request.user == message.user %}

               <a href="{% url 'base:delete_message' message.id  %}">Delete</a>
               {% endif %}
               <hr>
            </div>
          -->


        <div class="activities">
            <div class="activities__header">
              <h2>Recent Activities</h2>
            </div>
            {% for message in room_messages %}
            <div class="activities__box">
              <div class="activities__boxHeader roomListRoom__header">
                <a href="{% url 'users:user-profile' message.user.id %}" class="roomListRoom__author">
                  <div class="avatar avatar--small">
                    <img src="{{message.user.profile.image.url}}" />
                  </div>
                  <p>
                    @{{message.user}}
                    <span>{{message.created|timesince}}</span>
                  </p>
                </a>
                {% if request.user == message.user %}
                <div class="roomListRoom__actions">
                  <a href="{% url 'base:delete_message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                      ></path>
                    </svg>
                  </a>
                </div>
                {% endif %} 
              </div>
              <div class="activities__boxContent">
                <p>replied to post “<a href="{% url 'base:room' message.room.id%}">{{message.room.name}}</a>”</p>
                <div class="activities__boxRoomContent">
                  {{message}}
                </div>
              </div>
            </div>
            {% endfor %}
          </div>

base/templates/base/feed_component.html
<!-- <div>
    
    <div>
         {% if request.user == room.host %}
        <a href="{% url 'base:update_room' room.id %}">Edit</a>
        <a href="{% url 'base:delete_room' room.id %}">Delete</a>
        {% endif %}
        <a href="">@</a>
        <h5>{{room.id}} -- <a href="{{room.get_absolute_url}}">{{ room.name }}</a></h5>
        <small>{{room.topic.name}}</small>
        <hr>
    </div>
   
</div> -->
{% for room in page_obj %}

<div class="roomListRoom">
    <div class="roomListRoom__header">
      <a href="{% url 'users:user-profile' room.host.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small active">
          <img src="{{room.host.profile.image.url}}" />
        </div>
        <span>@{{room.host.username}}</span>
      </a>
      <div class="roomListRoom__actions">
        <span>{{room.created|timesince}}</span>
      </div>
    </div>
    <div class="roomListRoom__content">
      <a href="{{room.get_absolute_url}}">{{ room.name }}</a>
      <p>
        {{room.description|slice:':200'}}
      </p>
    </div>
    <div class="roomListRoom__meta">
      <a class="roomListRoom__joined">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>user-group</title>
          <path
            d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
          ></path>
          <path
            d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
          ></path>
          <path
            d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
          ></path>
          <path
            d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
          ></path>
        </svg>
        {{room.participants.count}} Joined
      </a>
      <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
  </div>
  {% endfor %}

base/templates/base/home.html
{% extends 'main.html' %}
{% block title %} Rooms {% endblock title %}

{% block content%}
    <main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->
        {% include 'topic_component.html' %}
        
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form action="{% url 'base:home' %}" method="get" class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{% url 'base:topics' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="{% url 'base:activities' %}">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{room_count}} Rooms available</p>
            </div>
            <a class="btn btn--main" href="{% url 'base:create_room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>
          {% include 'feed_component.html' %} 
          {% include 'paginator.html' %} 
        </div>
        <!-- Room List End -->

        <!-- Activities Start -->
          {% include 'activity_component.html' %} 
        <!-- Activities End -->
      </div>
    </main>

    {% endblock %}

base/templates/base/login_register.html
{% extends 'main.html' %} 

{% block content %}
<div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<!--login -->
    <main class="auth layout">
      {% if page == 'login' %} 
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <h3>Login</h3>
            </div>
          </div>
          <div class="layout__body">
            <h2 class="auth__tagline">Find your study partner</h2>

            <form class="form" action="" method="post">
              {% csrf_token %}
              <div class="form__group form__group">
                <label for="room_name">Username</label>
                <input id="username" name="username" type="text" placeholder="e.g. dennis_ivy" />
              </div>
              <div class="form__group">
                <label for="password">Password</label>
                <input
                  id="password"
                  name="password"
                  type="password"
                  placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
                />
              </div>

              <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path>
                </svg>

                Login
              </button>
            </form>

            <div class="auth__action">
              <p>Haven't signed up yet?</p>
              <a href="{% url 'base:register' %}" class="btn btn--link">Sign Up</a>
            </div>
          </div>
        </div>
      </div>

<!-- endlogin-->
{% else %}

<!-- register-->
<div>
  <div class="container" >
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Sign up</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your study partner</h2>

        <form class="form" action="" method="post"> 
            {% csrf_token %}
          {% for field in form %} 
     
          <div class="form__group">
            <label >{{field.label}}</label>
            {{field}}
          </div>
          {% endfor %}

         

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Sign Up
          </button>
        </form>

        <div class="auth__action">
          <p>Already have an account?</p>
          <a href="{% url 'base:login' %}" class="btn btn--link">Log In</a>
        </div>
      </div>
    </div>
  </div>
  
  {% endif %} 
</main>
<!-- endregister-->


{% endblock %} 

base/templates/base/profile.html
{% extends 'main.html' %} 

{% block content %} 
  <main class="profile-page layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      {% include 'topic_component.html' %} 
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              <img src="{{profile.image.url}}" />
            </div>
          </div>
          <div class="profile__info">
            <h3>{{profile.user.first_name}} {{profile.user.last_name}} </h3>
            <p>@{{profile.user.username}}</p>
            {% if user == profile.user %}
            <a href="{% url 'base:edit_user' user.id %}" class="btn btn--main btn--pill">Edit Profile</a>
            {% endif %}
          </div>
          <div class="profile__about">
            <h3>About</h3>
            <p>
              {{profile.bio}}
            </p>
          </div>
        </div>

        <div class="roomList__header">
          <div>
            <h2>Study Rooms Hosted by {{profile.user.username}}</a>
            </h2>
          </div>
        </div>
      {% include 'feed_component.html' %}
      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      {% include 'activity_component.html' %} 
      <!-- Activities End -->
    </div>
  </main>
{% endblock %} 

base/templates/base/room.html
{% extends 'main.html' %}
{% block title %} Rooms Detail {% endblock title %}

{% block content %} 
    <main class="profile-page layout layout--2">
      <div class="container">
        <!-- Room Start -->
        <div class="room">
          <div class="room__top">
            <div class="room__topLeft">
              <a href="{% url 'base:home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Study Room</h3>
            </div>
                {% if room.host == user %}
            <div class="room__topRight">
              <a href="{% url 'base:update_room' room.id %}">
                <svg
                  enable-background="new 0 0 24 24"
                  height="32"
                  viewBox="0 0 24 24"
                  width="32"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <title>edit</title>
                  <g>
                    <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                  </g>
                  <g>
                    <g>
                      <path
                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                      />
                    </g>
                    <g>
                      <path
                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                      />
                    </g>
                  </g>
                </svg>
              </a>
              <a href="{% url 'base:delete_room' room.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
            </div>
            {% endif %}

      
          </div>
          <div class="room__box scroll">
            <div class="room__header scroll">
              <div class="room__info">
                <h3>{{room.name}}</h3>
                <span>{{ room.created|timesince }}</span>
              </div>
              <div class="room__hosted">
                <p>Hosted By</p>
                <a href="#" class="room__author">
                  <div class="avatar avatar--small">
                    <img src="{{room.host.profile.image.url}}" />
                  </div>
                  <span>@{{room.host.username}}</span>
                </a>
              </div>
              <div class="room__details">
                {{ room.description }}
                
              </div>
              <span class="room__topics">{{room.topic}}</span>
            </div>
            <div class="room__conversation">
              <div class="threads scroll">
                {% for message in messages %} 
                <div class="thread">
                  <div class="thread__top">
                    <div class="thread__author">
                      <a href="{% url 'users:user-profile' message.user.id %}" class="thread__authorInfo">
                        <div class="avatar avatar--small">
                          <img src="{{message.user.profile.image.url}}" />
                        </div>
                        <span>@{{message.user.username}}</span>
                      </a>
                      <span class="thread__date">{{message.created|timesince}}</span>
                    </div>
                    {% if user == message.user %}
                    <a href="{% url 'base:delete_message' message.id%}">
                    <div class="thread__delete">
                      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>remove</title>
                        <path
                          d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                        ></path>
                      </svg>
                    </div>
                  </a>
                  {% endif %}
                  </div>
                  <div class="thread__details">
                    {{message.body}}
                  </div>
                </div> 
                {% endfor %} 
              </div>
            </div>
          </div>
          
          <div class="room__message">
            <form action="" method="post">
              {% csrf_token%}
              {% if request.user.is_authenticated %}<input name="body" placeholder="Write your message here..." />{%endif%}</form>
          </div>
        </div>
         
        <!-- Room End -->

        <!--   Start -->
        <div class="participants">
          
          <h3 class="participants__top">Participants <span>({{participants.count}} Joined)</span></h3>
          <div class="participants__list scroll">
            {% for participant in participants %}
            <a href="{% url 'users:user-profile' participant.id %}" class="participant">
              <div class="avatar avatar--medium">
                <img src="{{participant.profile.image.url}}" />
              </div>
              <p>
                {% if participant.first_name %}{{ participant.first_name}}{% else%} {{participant.username}} {%endif%} 
                
                <span>@ {{participant.username}}</span>
              </p>
            </a>
            {% endfor %}
          </div>
        </div>
        <!--  End -->
      </div>
    </main>
    <script src="script.js"></script>
{% endblock %}

base/templates/base/topic_component.html
<div class="topics">
   <div class="topics__header">
     <h2>Browse Topics</h2>
   </div>
   <ul class="topics__list">
     <li>
       <a href="{% url 'base:home' %}" class="active">All <span>{{topic.count}}</span></a>
     </li>
     {% for tpc in topic %} 
     <li>
       <a href="{% url 'base:home' %}?q={{tpc.name}}">{{tpc}} <span>{{tpc.room_set.all.count}}</span></a>
     </li>
     {% endfor %} 
   </ul>
   <a class="btn btn--link" href="{% url 'base:topics' %}">
     More
     <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
       <title>chevron-down</title>
       <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
     </svg>
   </a>
 </div>